/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module top(a, b, c);
  wire \$abc$176$n14_1 ;
  wire \$abc$176$n15 ;
  wire \$abc$176$n16_1 ;
  wire \$abc$176$n17_1 ;
  wire \$abc$176$n18_1 ;
  wire \$abc$176$n19_1 ;
  wire \$abc$176$n20_1 ;
  wire \$abc$176$n21_1 ;
  wire \$abc$176$n22_1 ;
  wire \$abc$176$n25_1 ;
  wire \$abc$176$n28 ;
  input [3:0] a;
  input [3:0] b;
  output [7:0] c;
  NAND \$abc$176$auto$blifparse.cc:286:parse_blif$177  (
    .A(b[3]),
    .B(a[3]),
    .Y(\$abc$176$n14_1 )
  );
  AND \$abc$176$auto$blifparse.cc:286:parse_blif$178  (
    .A(b[2]),
    .B(a[2]),
    .Y(\$abc$176$n15 )
  );
  NAND \$abc$176$auto$blifparse.cc:286:parse_blif$179  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$176$n16_1 )
  );
  NAND \$abc$176$auto$blifparse.cc:286:parse_blif$180  (
    .A(b[0]),
    .B(a[0]),
    .Y(\$abc$176$n17_1 )
  );
  NOR \$abc$176$auto$blifparse.cc:286:parse_blif$181  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$176$n18_1 )
  );
  OAI21 \$abc$176$auto$blifparse.cc:286:parse_blif$182  (
    .A(\$abc$176$n18_1 ),
    .B(\$abc$176$n17_1 ),
    .C(\$abc$176$n16_1 ),
    .Y(\$abc$176$n19_1 )
  );
  XOR \$abc$176$auto$blifparse.cc:286:parse_blif$183  (
    .A(b[2]),
    .B(a[2]),
    .Y(\$abc$176$n20_1 )
  );
  AOI21 \$abc$176$auto$blifparse.cc:286:parse_blif$184  (
    .A(\$abc$176$n20_1 ),
    .B(\$abc$176$n19_1 ),
    .C(\$abc$176$n15 ),
    .Y(\$abc$176$n21_1 )
  );
  NOR \$abc$176$auto$blifparse.cc:286:parse_blif$185  (
    .A(b[3]),
    .B(a[3]),
    .Y(\$abc$176$n22_1 )
  );
  OAI21 \$abc$176$auto$blifparse.cc:286:parse_blif$186  (
    .A(\$abc$176$n22_1 ),
    .B(\$abc$176$n21_1 ),
    .C(\$abc$176$n14_1 ),
    .Y(c[4])
  );
  XOR \$abc$176$auto$blifparse.cc:286:parse_blif$187  (
    .A(b[0]),
    .B(a[0]),
    .Y(c[0])
  );
  XOR \$abc$176$auto$blifparse.cc:286:parse_blif$188  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$176$n25_1 )
  );
  XNOR \$abc$176$auto$blifparse.cc:286:parse_blif$189  (
    .A(\$abc$176$n25_1 ),
    .B(\$abc$176$n17_1 ),
    .Y(c[1])
  );
  XOR \$abc$176$auto$blifparse.cc:286:parse_blif$190  (
    .A(\$abc$176$n20_1 ),
    .B(\$abc$176$n19_1 ),
    .Y(c[2])
  );
  XOR \$abc$176$auto$blifparse.cc:286:parse_blif$191  (
    .A(b[3]),
    .B(a[3]),
    .Y(\$abc$176$n28 )
  );
  XNOR \$abc$176$auto$blifparse.cc:286:parse_blif$192  (
    .A(\$abc$176$n28 ),
    .B(\$abc$176$n21_1 ),
    .Y(c[3])
  );
  assign c[7:5] = 3'b000;
endmodule
