/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module top(a, b, c);
  wire \$abc$309$n100 ;
  wire \$abc$309$n101 ;
  wire \$abc$309$n103 ;
  wire \$abc$309$n17 ;
  wire \$abc$309$n19 ;
  wire \$abc$309$n20 ;
  wire \$abc$309$n21 ;
  wire \$abc$309$n22 ;
  wire \$abc$309$n24 ;
  wire \$abc$309$n25 ;
  wire \$abc$309$n26 ;
  wire \$abc$309$n27 ;
  wire \$abc$309$n28 ;
  wire \$abc$309$n29 ;
  wire \$abc$309$n30 ;
  wire \$abc$309$n31 ;
  wire \$abc$309$n32 ;
  wire \$abc$309$n33 ;
  wire \$abc$309$n34 ;
  wire \$abc$309$n35 ;
  wire \$abc$309$n37 ;
  wire \$abc$309$n38 ;
  wire \$abc$309$n39 ;
  wire \$abc$309$n40 ;
  wire \$abc$309$n41 ;
  wire \$abc$309$n42 ;
  wire \$abc$309$n43 ;
  wire \$abc$309$n44_1 ;
  wire \$abc$309$n45_1 ;
  wire \$abc$309$n46 ;
  wire \$abc$309$n47 ;
  wire \$abc$309$n48 ;
  wire \$abc$309$n49 ;
  wire \$abc$309$n50 ;
  wire \$abc$309$n51_1 ;
  wire \$abc$309$n52 ;
  wire \$abc$309$n53_1 ;
  wire \$abc$309$n54 ;
  wire \$abc$309$n55_1 ;
  wire \$abc$309$n57 ;
  wire \$abc$309$n58 ;
  wire \$abc$309$n59 ;
  wire \$abc$309$n60 ;
  wire \$abc$309$n61 ;
  wire \$abc$309$n62 ;
  wire \$abc$309$n63 ;
  wire \$abc$309$n64 ;
  wire \$abc$309$n65_1 ;
  wire \$abc$309$n66_1 ;
  wire \$abc$309$n67_1 ;
  wire \$abc$309$n68_1 ;
  wire \$abc$309$n69_1 ;
  wire \$abc$309$n70_1 ;
  wire \$abc$309$n71_1 ;
  wire \$abc$309$n72_1 ;
  wire \$abc$309$n73_1 ;
  wire \$abc$309$n74_1 ;
  wire \$abc$309$n75 ;
  wire \$abc$309$n76 ;
  wire \$abc$309$n78 ;
  wire \$abc$309$n79 ;
  wire \$abc$309$n80 ;
  wire \$abc$309$n81 ;
  wire \$abc$309$n82 ;
  wire \$abc$309$n83 ;
  wire \$abc$309$n84 ;
  wire \$abc$309$n85 ;
  wire \$abc$309$n86 ;
  wire \$abc$309$n87 ;
  wire \$abc$309$n88 ;
  wire \$abc$309$n89 ;
  wire \$abc$309$n90 ;
  wire \$abc$309$n92 ;
  wire \$abc$309$n93 ;
  wire \$abc$309$n94 ;
  wire \$abc$309$n95 ;
  wire \$abc$309$n96 ;
  wire \$abc$309$n97 ;
  wire \$abc$309$n98 ;
  wire \$abc$309$n99 ;
  input [3:0] a;
  input [3:0] b;
  output [7:0] c;
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$310  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$309$n17 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$311  (
    .A(b[0]),
    .B(a[0]),
    .Y(c[0])
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$312  (
    .A(c[0]),
    .B(\$abc$309$n17 ),
    .Y(\$abc$309$n19 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$313  (
    .A(a[1]),
    .B(b[0]),
    .Y(\$abc$309$n20 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$314  (
    .A(b[1]),
    .B(a[0]),
    .Y(\$abc$309$n21 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$315  (
    .A(\$abc$309$n21 ),
    .B(\$abc$309$n20 ),
    .Y(\$abc$309$n22 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$316  (
    .A(\$abc$309$n22 ),
    .B(\$abc$309$n19 ),
    .Y(c[1])
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$317  (
    .A(b[2]),
    .B(a[0]),
    .Y(\$abc$309$n24 )
  );
  NOT \$abc$309$auto$blifparse.cc:286:parse_blif$318  (
    .A(\$abc$309$n24 ),
    .Y(\$abc$309$n25 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$319  (
    .A(b[1]),
    .B(a[2]),
    .Y(\$abc$309$n26 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$320  (
    .A(\$abc$309$n26 ),
    .B(\$abc$309$n20 ),
    .Y(\$abc$309$n27 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$321  (
    .A(a[2]),
    .B(b[0]),
    .Y(\$abc$309$n28 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$322  (
    .A(\$abc$309$n28 ),
    .B(\$abc$309$n17 ),
    .Y(\$abc$309$n29 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$323  (
    .A(\$abc$309$n29 ),
    .B(\$abc$309$n27 ),
    .Y(\$abc$309$n30 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$324  (
    .A(\$abc$309$n30 ),
    .B(\$abc$309$n25 ),
    .Y(\$abc$309$n31 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$325  (
    .A(\$abc$309$n30 ),
    .B(\$abc$309$n25 ),
    .Y(\$abc$309$n32 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$326  (
    .A(\$abc$309$n32 ),
    .B(\$abc$309$n31 ),
    .Y(\$abc$309$n33 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$327  (
    .A(\$abc$309$n33 ),
    .B(\$abc$309$n19 ),
    .Y(\$abc$309$n34 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$328  (
    .A(\$abc$309$n33 ),
    .B(\$abc$309$n19 ),
    .Y(\$abc$309$n35 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$329  (
    .A(\$abc$309$n35 ),
    .B(\$abc$309$n34 ),
    .Y(c[2])
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$330  (
    .A(b[3]),
    .B(a[0]),
    .Y(\$abc$309$n37 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$331  (
    .A(\$abc$309$n31 ),
    .B(\$abc$309$n27 ),
    .Y(\$abc$309$n38 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$332  (
    .A(b[2]),
    .B(a[1]),
    .Y(\$abc$309$n39 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$333  (
    .A(b[1]),
    .B(a[3]),
    .Y(\$abc$309$n40 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$334  (
    .A(\$abc$309$n40 ),
    .B(\$abc$309$n28 ),
    .Y(\$abc$309$n41 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$335  (
    .A(a[3]),
    .B(b[0]),
    .Y(\$abc$309$n42 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$336  (
    .A(\$abc$309$n42 ),
    .B(\$abc$309$n26 ),
    .Y(\$abc$309$n43 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$337  (
    .A(\$abc$309$n43 ),
    .B(\$abc$309$n41 ),
    .Y(\$abc$309$n44_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$338  (
    .A(\$abc$309$n44_1 ),
    .B(\$abc$309$n39 ),
    .Y(\$abc$309$n45_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$339  (
    .A(\$abc$309$n44_1 ),
    .B(\$abc$309$n39 ),
    .Y(\$abc$309$n46 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$340  (
    .A(\$abc$309$n46 ),
    .B(\$abc$309$n45_1 ),
    .Y(\$abc$309$n47 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$341  (
    .A(\$abc$309$n47 ),
    .B(\$abc$309$n38 ),
    .Y(\$abc$309$n48 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$342  (
    .A(\$abc$309$n47 ),
    .B(\$abc$309$n38 ),
    .Y(\$abc$309$n49 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$343  (
    .A(\$abc$309$n49 ),
    .B(\$abc$309$n48 ),
    .Y(\$abc$309$n50 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$344  (
    .A(\$abc$309$n50 ),
    .B(\$abc$309$n37 ),
    .Y(\$abc$309$n51_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$345  (
    .A(\$abc$309$n50 ),
    .B(\$abc$309$n37 ),
    .Y(\$abc$309$n52 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$346  (
    .A(\$abc$309$n52 ),
    .B(\$abc$309$n51_1 ),
    .Y(\$abc$309$n53_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$347  (
    .A(\$abc$309$n53_1 ),
    .B(\$abc$309$n34 ),
    .Y(\$abc$309$n54 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$348  (
    .A(\$abc$309$n53_1 ),
    .B(\$abc$309$n34 ),
    .Y(\$abc$309$n55_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$349  (
    .A(\$abc$309$n55_1 ),
    .B(\$abc$309$n54 ),
    .Y(c[3])
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$350  (
    .A(\$abc$309$n51_1 ),
    .B(\$abc$309$n48 ),
    .Y(\$abc$309$n57 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$351  (
    .A(b[3]),
    .B(a[1]),
    .Y(\$abc$309$n58 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$352  (
    .A(\$abc$309$n45_1 ),
    .B(\$abc$309$n41 ),
    .Y(\$abc$309$n59 )
  );
  NOT \$abc$309$auto$blifparse.cc:286:parse_blif$353  (
    .A(\$abc$309$n26 ),
    .Y(\$abc$309$n60 )
  );
  NAND \$abc$309$auto$blifparse.cc:286:parse_blif$354  (
    .A(b[2]),
    .B(a[3]),
    .Y(\$abc$309$n61 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$355  (
    .A(\$abc$309$n61 ),
    .B(\$abc$309$n60 ),
    .Y(\$abc$309$n62 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$356  (
    .A(b[2]),
    .B(a[2]),
    .Y(\$abc$309$n63 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$357  (
    .A(\$abc$309$n63 ),
    .B(\$abc$309$n40 ),
    .Y(\$abc$309$n64 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$358  (
    .A(\$abc$309$n64 ),
    .B(\$abc$309$n62 ),
    .Y(\$abc$309$n65_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$359  (
    .A(\$abc$309$n65_1 ),
    .B(\$abc$309$n59 ),
    .Y(\$abc$309$n66_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$360  (
    .A(\$abc$309$n65_1 ),
    .B(\$abc$309$n59 ),
    .Y(\$abc$309$n67_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$361  (
    .A(\$abc$309$n67_1 ),
    .B(\$abc$309$n66_1 ),
    .Y(\$abc$309$n68_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$362  (
    .A(\$abc$309$n68_1 ),
    .B(\$abc$309$n58 ),
    .Y(\$abc$309$n69_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$363  (
    .A(\$abc$309$n68_1 ),
    .B(\$abc$309$n58 ),
    .Y(\$abc$309$n70_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$364  (
    .A(\$abc$309$n70_1 ),
    .B(\$abc$309$n69_1 ),
    .Y(\$abc$309$n71_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$365  (
    .A(\$abc$309$n71_1 ),
    .B(\$abc$309$n57 ),
    .Y(\$abc$309$n72_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$366  (
    .A(\$abc$309$n71_1 ),
    .B(\$abc$309$n57 ),
    .Y(\$abc$309$n73_1 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$367  (
    .A(\$abc$309$n73_1 ),
    .B(\$abc$309$n72_1 ),
    .Y(\$abc$309$n74_1 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$368  (
    .A(\$abc$309$n74_1 ),
    .B(\$abc$309$n54 ),
    .Y(\$abc$309$n75 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$369  (
    .A(\$abc$309$n74_1 ),
    .B(\$abc$309$n54 ),
    .Y(\$abc$309$n76 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$370  (
    .A(\$abc$309$n76 ),
    .B(\$abc$309$n75 ),
    .Y(c[4])
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$371  (
    .A(\$abc$309$n75 ),
    .B(\$abc$309$n72_1 ),
    .Y(\$abc$309$n78 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$372  (
    .A(\$abc$309$n69_1 ),
    .B(\$abc$309$n66_1 ),
    .Y(\$abc$309$n79 )
  );
  NOT \$abc$309$auto$blifparse.cc:286:parse_blif$373  (
    .A(\$abc$309$n79 ),
    .Y(\$abc$309$n80 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$374  (
    .A(\$abc$309$n61 ),
    .B(\$abc$309$n26 ),
    .Y(\$abc$309$n81 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$375  (
    .A(b[3]),
    .B(a[2]),
    .Y(\$abc$309$n82 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$376  (
    .A(\$abc$309$n82 ),
    .B(\$abc$309$n81 ),
    .Y(\$abc$309$n83 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$377  (
    .A(\$abc$309$n82 ),
    .B(\$abc$309$n81 ),
    .Y(\$abc$309$n84 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$378  (
    .A(\$abc$309$n84 ),
    .B(\$abc$309$n83 ),
    .Y(\$abc$309$n85 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$379  (
    .A(\$abc$309$n85 ),
    .B(\$abc$309$n80 ),
    .Y(\$abc$309$n86 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$380  (
    .A(\$abc$309$n85 ),
    .B(\$abc$309$n80 ),
    .Y(\$abc$309$n87 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$381  (
    .A(\$abc$309$n87 ),
    .B(\$abc$309$n86 ),
    .Y(\$abc$309$n88 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$382  (
    .A(\$abc$309$n88 ),
    .B(\$abc$309$n78 ),
    .Y(\$abc$309$n89 )
  );
  NAND \$abc$309$auto$blifparse.cc:286:parse_blif$383  (
    .A(\$abc$309$n88 ),
    .B(\$abc$309$n78 ),
    .Y(\$abc$309$n90 )
  );
  NAND \$abc$309$auto$blifparse.cc:286:parse_blif$384  (
    .A(\$abc$309$n90 ),
    .B(\$abc$309$n89 ),
    .Y(c[5])
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$385  (
    .A(b[3]),
    .B(a[3]),
    .Y(\$abc$309$n92 )
  );
  NOT \$abc$309$auto$blifparse.cc:286:parse_blif$386  (
    .A(\$abc$309$n92 ),
    .Y(\$abc$309$n93 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$387  (
    .A(\$abc$309$n83 ),
    .B(\$abc$309$n62 ),
    .Y(\$abc$309$n94 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$388  (
    .A(\$abc$309$n94 ),
    .B(\$abc$309$n93 ),
    .Y(\$abc$309$n95 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$389  (
    .A(\$abc$309$n94 ),
    .B(\$abc$309$n93 ),
    .Y(\$abc$309$n96 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$390  (
    .A(\$abc$309$n96 ),
    .B(\$abc$309$n95 ),
    .Y(\$abc$309$n97 )
  );
  NOR \$abc$309$auto$blifparse.cc:286:parse_blif$391  (
    .A(\$abc$309$n87 ),
    .B(\$abc$309$n78 ),
    .Y(\$abc$309$n98 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$392  (
    .A(\$abc$309$n98 ),
    .B(\$abc$309$n86 ),
    .Y(\$abc$309$n99 )
  );
  NAND \$abc$309$auto$blifparse.cc:286:parse_blif$393  (
    .A(\$abc$309$n99 ),
    .B(\$abc$309$n97 ),
    .Y(\$abc$309$n100 )
  );
  OR \$abc$309$auto$blifparse.cc:286:parse_blif$394  (
    .A(\$abc$309$n99 ),
    .B(\$abc$309$n97 ),
    .Y(\$abc$309$n101 )
  );
  AND \$abc$309$auto$blifparse.cc:286:parse_blif$395  (
    .A(\$abc$309$n101 ),
    .B(\$abc$309$n100 ),
    .Y(c[6])
  );
  NOT \$abc$309$auto$blifparse.cc:286:parse_blif$396  (
    .A(\$abc$309$n95 ),
    .Y(\$abc$309$n103 )
  );
  NAND \$abc$309$auto$blifparse.cc:286:parse_blif$397  (
    .A(\$abc$309$n100 ),
    .B(\$abc$309$n103 ),
    .Y(c[7])
  );
endmodule
